---
permalink: concept-active-iq-learn-about-active-iq.html 
sidebar: sidebar 
keywords: solidfire, active, iq, learn 
summary: SolidFire Active IQ에 대해 자세히 알아보십시오. 
---
= SolidFire Active IQ에 대해 자세히 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
SolidFire Active IQ를 사용하기 전에 SolidFire Active IQ의 작동 방식과 이 기능이 수집하는 정보에 대해 알고 있어야 합니다.



== SolidFire Active IQ의 작동 방식

Collector 및 원격 측정과 같은 서비스는 관리 노드에서 실행됩니다. 이러한 서비스는 클러스터에 대한 읽기 전용 액세스로 구성되고 스케줄에 따라 클러스터에 API 호출을 수행하여 주요 성능, 용량 및 상태 메트릭을 수집합니다. 이 정보는 HTTPS를 통해 SolidFire Active IQ 클라우드 데이터베이스에 업로드되며, 이 데이터베이스는 SolidFire Active IQ UI를 통해 귀사와 NetApp Support에서 처리 및 제공됩니다. SolidFire Active IQ UI에서 클러스터에 대해 수신한 최신 API 페이로드 및 수집 간격을 보려면 SSO 자격 증명을 사용하여 로그인하고 * Reporting * 드롭다운 메뉴에서 * API Collection * 을 선택합니다.

link:https://activeiq.solidfire.com/["Access SolidFire Active IQ(로그인 필요)"^]



== SolidFire Active IQ에서 수집하는 정보

SolidFire Active IQ는 볼륨, 클러스터, 노드, 성능 및 구성에 대한 정보를 수집합니다.

* 볼륨, 스냅샷 및 계정 노드 ID와 같은 리소스 ID입니다
* 클러스터 및 볼륨의 성능 및 용량 데이터
* 오류 및 이벤트 기록
* NetApp HCI 및 Element 소프트웨어 버전
* QoS(서비스 품질) 구성
* 크기, 생성 날짜 등과 같은 볼륨 세부 정보
* 볼륨 액세스 그룹 및 세션 구성
* 노드 및 클러스터 네트워크 구성


SolidFire Active IQ는 다음과 같은 고객의 중요한 정보를 수집하지 않습니다.

* 실제 최종 사용자 데이터
* 암호
* CHAP(Challenge-Handshake Authentication Protocol) 암호
* 클러스터 관리 사용자 정보입니다




== 자세한 내용을 확인하십시오

https://www.netapp.com/support-and-training/documentation/["NetApp 제품 설명서"^]
