---
permalink: task_active_iq_replication.html 
sidebar: sidebar 
keywords: solidfire, active, iq, replication 
summary: SolidFire Active IQ의 복제 페이지에 대해 자세히 알아보십시오. 
---
= 복제
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
선택한 클러스터의 측면 패널에서 사용할 수 있는 * Replication * 페이지에서는 클러스터 쌍과 볼륨 쌍에 대한 정보를 제공합니다.

클러스터 쌍 및 볼륨 쌍 페이지에 대해 자세히 알아보십시오.

* <<cluster_pairs,클러스터 쌍>>
* <<volume_pairs,볼륨 쌍>>




== 클러스터 쌍

선택한 클러스터의 * Replication * > * Cluster Pairs * 페이지에서 클러스터 쌍에 대한 다음 정보를 볼 수 있습니다.

[cols="30,70"]
|===
| 제목 | 설명 


| 클러스터 쌍 ID입니다 | 클러스터 쌍이 생성될 때 지정한 ID 번호입니다. 


| 원격 클러스터 이름 | 페어의 원격 클러스터 이름입니다. 


| 원격 MVIP | 관리 원격 클러스터의 가상 IP입니다. 


| 볼륨 복제 | 페어링된 클러스터에 복제된 볼륨의 수를 나타냅니다. 


| 상태 | 클러스터 쌍의 상태입니다. 


| UUID입니다 | 범용 고유 식별자입니다. 
|===


== 볼륨 쌍

선택한 클러스터의 * Replication * > * Volume Pairs * 페이지에서 볼륨 쌍에 대한 다음 정보를 볼 수 있습니다.

[cols="30,70"]
|===
| 제목 | 설명 


| 볼륨 ID입니다 | 볼륨을 생성할 때 지정된 ID 번호입니다. 


| 계정 ID입니다 | 볼륨에 할당된 계정의 ID입니다. 


| 볼륨 상태 | 복제 볼륨의 상태입니다. 


| 복제 모드 | 볼륨 쌍에 대해 선택된 모드의 유형입니다. 


| 방향  a| 
볼륨 데이터의 방향을 나타냅니다.

* 소스: 데이터가 클러스터 외부의 타겟에 기록되고 있음을 나타냅니다.
* 타겟: 데이터가 외부 소스에서 로컬 볼륨에 기록되고 있음을 나타냅니다.




| 비동기 지연  a| 
볼륨이 원격 클러스터와 마지막으로 동기화된 이후의 시간입니다. 볼륨이 페어링되지 않은 경우 null입니다.


NOTE: 활성 복제 상태의 타겟 볼륨은 항상 0의 비동기 지연을 가집니다. 타겟 볼륨은 복제 중에 시스템을 인식하고 비동기식 지연이 항상 정확하다고 가정합니다.



| 원격 클러스터 | 볼륨이 상주하는 원격 클러스터의 이름입니다. 


| 원격 볼륨 ID입니다 | 원격 클러스터에 있는 볼륨의 볼륨 ID입니다. 
|===


== 자세한 내용을 확인하십시오

https://www.netapp.com/support-and-training/documentation/["NetApp 제품 설명서"^]
