---
permalink: task-active-iq-virtual-machines.html 
sidebar: sidebar 
keywords: solidfire, active, iq, virtual, machines, vm 
summary: SolidFire Active IQ의 가상 머신 페이지에 대해 자세히 알아보십시오. 
---
= 가상 머신
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
선택한 NetApp HCI 클러스터의 측면 패널에서 사용할 수 있는 * 가상 머신 * 페이지에서 가상 머신(VM)에 대한 CPU 및 스토리지 관련 상태 정보를 볼 수 있습니다.


NOTE: 가상 머신 * 페이지는 NetApp HCI 클러스터에서만 사용할 수 있습니다.

UI에 표시되는 VM 데이터의 필터링 및 이해에 대해 알아봅니다.



== 가상 머신 세부 정보를 봅니다

선택한 클러스터의 측면 패널에서 사용할 수 있는 * Virtual Machines * 페이지는 클러스터와 연결된 각 활성 VM에 대한 정보를 제공합니다.

모든 SolidFire Active IQ 페이지에서 사용할 수 있는 일반 필터링 옵션 외에도 * 가상 머신 * 페이지에는 일반적인 VM 가용성 상태를 확인하기 위해 선택할 수 있는 빠른 필터 버튼이 있습니다.

정보 표시줄은 다음 데이터에 대한 간략한 개요를 제공합니다.

* 가상 머신: 스토리지 클러스터와 연결된 VM의 수 및 다양한 가용성 상태입니다.
* 상태: VM에 대한 경고 또는 오류 수입니다.
* 프로비저닝된 리소스: 스토리지 클러스터와 연결된 모든 VM에 대한 총 스토리지 및 메모리 리소스입니다.


[cols="30,70"]
|===
| 제목 | 설명 


| 이름 | VM의 이름입니다. 


| 상태  a| 
VM의 가용성 상태:

* 정상: VM이 예상대로 응답 중입니다.
* 경고: 경고가 보고되었습니다. 자세한 내용은 vSphere를 참조하십시오.
* 위험: 심각한 오류가 보고되었습니다. 자세한 내용은 vSphere를 참조하십시오.
* 알 수 없음: VM에 액세스할 수 없습니다.




| 전원 상태 | VM의 전원이 켜져 있는지, 전원이 꺼져 있는지 또는 일시 중지되었는지 여부를 나타냅니다. 


| vCenter IP입니다 | vCenter Server의 IP 주소입니다. 


| CPU 수 | 각 VM의 CPU 수 


| 호스트 메모리 사용량 | 가상 머신에서 사용 중인 ESXi 호스트 메모리의 양입니다. 


| CPU 사용량 | VM에서 사용 가능한 총 CPU의 백분율로 사용된 활성 가상 CPU의 비율입니다. 


| 사용된 용량 | 사용 중인 VM 스토리지 리소스의 비율입니다. 


| 최대 디스크 지연 시간 | 감지된 최대 디스크 지연 시간(밀리초). 


| 알람 | VM에서 트리거된 vSphere 알람의 수입니다. 
|===


== 자세한 내용을 확인하십시오

https://www.netapp.com/support-and-training/documentation/["NetApp 제품 설명서"^]
